### PR TITLE
Adding a "remove" functionality for preauthorizations, fixing a typo in the details function, adding a few missing semicolons

### PR DESCRIPTION
**Pull request by itamarwe**
The main goal of this pull request is to add the remove functionality for preauthorizations, to enable users to cancel a preauthorization.

### CODE REVIEW

**Comment by thomaschaaf** [comment]
Thank you for the commit. The code looks good. Sadly it can't be merged automatically. I will look at this later today.

**Comment by nponiros** [comment]
@itamarwe The code base you used to create the pull request seems to be rather old.

As far as I can see there is already a remove function for preauthorizations in the current version of paymill-node but the readme is not up to date

**Comment by thomaschaaf** [comment]
Oh @nponiros you are correct the code base does seem to be old. I will thus close the pull request and add the function to the read me.

**Comment by itamarwe** [comment]
@nponiros Yeah, I actually created this pull-request a while ago for the official "Paymill" fork and was frustrated that no one paid attention to it there. So I created this one here.
Nice to see that it was already implemented in the last upgrade.

**Comment by thomaschaaf** [comment]
This is the official repository. The other one is simply a fork. Would you suggest simply putting a link in that (paymill/paymill-node) repository which links here (komola/paymill-node)?

**Comment by itamarwe** [comment]
I mean it's quite confusing. Paymill links to the other repository from the "Docs" section of their website.
So either they link to this repository, or the other repository should be made the official one.

**Comment by d0mme-zz** [comment]
> Yeah, I actually created this pull-request a while ago for the official "Paymill" fork and was frustrated that no one paid attention to it there. So I created this one here.
> Nice to see that it was already implemented in the last upgrade.

We will change link from our fork to this one to avoid confusions. Sorry @itamarwe for not responding to your request for this long time. We hope to improve your response times here on GitHub.

**Pull request closed without merging**
