### PR TITLE
Various small fixes

### PR DESCRIPTION
**Pull request by nponiros**
Fixes include:
The addition of a jshintrc. Main.js was adjusted so the it can be successfully linted. (See also https://github.com/komola/paymill-node/issues/9)
For better error support the API calls should throw a TypeError instead of calling the (given) callback with a string. (See last comment in issue https://github.com/komola/paymill-node/issues/7).
Example 7 had a wrong file extension.
Add the error event in setup_response_handler.
Setup_response_handler function does not need to be called if no callback was given.

There are a number of changes (and some of them are rather opinionated) and I do not know if you are really interested in pulling it but perhaps some of the changes could be useful for you.

Regards
nponiros

### CODE REVIEW

**Comment by thomaschaaf** [comment]
Thanks for the changes I'll look into them

**Comment by Prinzhorn** [comment]
@nponiros are you using your fork in production? I am **very** interested in all of these changes you've made and more than willing to participate in maintaining a active fork. Or may we can get push access (@thomaschaaf)? Our business depends on this.

**Comment by sebastianhoitz** [comment]
Hey! Sorry for the long time of silence :/

First of all: Thank you very much for these awesome changes! I just took a look at them and they look very promising!

I just pulled your changes and tried to run the unit tests. Three things:
1. in the main.js file there is a duplicate `remove` method
2. it took me a while to figure out how to run the unit tests. It is pretty common for npm packages to have a `npm test` script that runs the unit tests for the current package.
3. all unit tests seem to have tabs for indentation, but the main.js file uses spaces.

When these things are solved I don't see a reason why not to pull these changes. And it won't be another few months until my response. Again, sorry for that :(

**Comment by sebastianhoitz** [comment]
I just changed those three things myself and merged your changes in.

I will push the npm version to 0.1.0 and publish to npm. Does that sound allright? :)

**Comment by Prinzhorn** [comment]
Aww Yiss :+1: 

I'm working on PayMill integration for the next days. So expect some useful feedback (also for those other issues I created).

**Comment by sebastianhoitz** [comment]
Sounds good! :+1:

**Comment by d0mme-zz** [comment]
Thanks for your support guys, we from Paymill appreciate your work! :+1:

**Comment by nponiros** [comment]
@sebastianhoitz 

Thanks for the merge and for the fixes. I can now again use the official repo in my project :)
yeah sorry for the mistakes. Was my first time using github pull request and I thought that it will only show the commits before the pull request and not include the ones after the pull request.. I know better now to use a special branch for fixes.

@Prinzhorn 

The fork was only used in a test system so far and I will switch back to this repo now as my changes were merged.

Its probably best if we can collaborate on this repo.

**Pull request merged**
